### ISSUE TITLE
Discord is not detecting EasyRP

### ISSUE THREAD

**Issue by Aelita4** [Pizzabelly/EasyRP#106]
I can't add EasyRP as game in Discord, it just does not show there
Everything is configured correctly, console does not show any errors, there is just info from config and "Displaying Presence for Raxxo#3928"
![Screenshot](https://user-images.githubusercontent.com/39732968/78425055-340f7900-7672-11ea-8feb-005b622aa6ea.png)

**Comment by zaneshaw** [comment]
Sorry for the late reply.
You need to edit the config.ini file and input your application's [client ID](https://imgur.com/a/nRAhqEX) which you can find in your [discord developer portal](https://discord.com/developers/applications). If you don't have an app yet, refer to the [readme.txt](https://pastebin.com/MsKjvXjz) in the release files. If you want images in your rich presence you need to add them in your application's art assets page which is in the dev portal also. Once you've done all this, you can leave **easyrp.exe** running in the background. Again sorry for the extremely late reply.

**Comment by Pera16** [comment]
I've done everything right, but still discord isn't detecting EasyRP.
http://prntscr.com/tctkpp

**Comment by zaneshaw** [comment]
> I've done everything right, but still discord isn't detecting EasyRP.
> http://prntscr.com/tctkpp

The rich presence will work without selecting it in-game activity.
Make sure you don't use your bot's client ID. Your applications client ID is in the "[General Information](https://imgur.com/a/R8cZLwQ)" tab on the dev console. Remember to leave the exe running.
Also, click the links I put in the last reply if you haven't already. Those might fix the issue. Plus check the exe for any errors.

**Comment by Pera16** [comment]
> > I've done everything right, but still discord isn't detecting EasyRP.
> > http://prntscr.com/tctkpp
> 
> The rich presence will work without selecting it in-game activity.
> Make sure you don't use your bot's client ID. Your applications client ID is in the "[General Information](https://imgur.com/a/R8cZLwQ)" tab on the dev console. Remember to leave the exe running.
> Also, click the links I put in the last reply if you haven't already. Those might fix the issue. Plus check the exe for any errors.

Thanks, I fixed it!

**Comment by Tanakiin** [comment]
How did you fix it
Cause I did all the things exactly as was said, and its still doesn't show up on Add Games

**Comment by zaneshaw** [comment]
You didn't read what I said. It doesn't show up on Add Games because it is not supposed to. Read it properly.

**Comment by Tanakiin** [comment]
Where is it supposed to appear then?

**Comment by zaneshaw** [comment]
Please re-read what I said.
> The rich presence will work without selecting it in-game activity.
Make sure you don't use your bot's client ID. Your applications client ID is in the "General Information" tab on the dev console. Remember to leave the exe running.
Also, click the links I put in the last reply if you haven't already. Those might fix the issue. Plus check the exe for any errors.

**Comment by Tanakiin** [comment]
I've done all of that but it isn't working.
The exe is running, I've entered the applications client ID, I've also double checked all the file names.
And it still doesnt work
I've re-read what you've said. If I'm missing something please point it out.

**Comment by Tanakiin** [comment]
Wait nvm, I unzipped it again and entered all the files.
Seems to have fixed it.
Thanks

**Comment by zaneshaw** [comment]
Glad you solved it! 👍

**Comment by zaneshaw** [comment]
@Raxxo Please close this issue.
