### ISSUE TITLE
Meson Build Failed

### ISSUE THREAD

**Issue by ALEEF02** [Pizzabelly/EasyRP#49]
When I try to build your project using Meson, I get this error:
`Build started at 2018-07-20T13:03:21.759307
Main binary: C:\Program Files\Meson\meson.exe
Python system: Windows
The Meson build system
Version: 0.47.1
Source dir: C:\Users\fordf\Downloads\EasyRP
Build dir: C:\Users\fordf\Downloads\EasyRP\builddir
Build type: native build
Project name: EasyRP
Project version: 3.0

meson.build:1:0: ERROR:  Unknown compiler(s): ['cl', 'c++', 'g++', 'clang++']
The follow exceptions were encountered:
Running "cl /?" gave "[WinError 2] The system cannot find the file specified"
Running "c++ --version" gave "[WinError 2] The system cannot find the file specified"
Running "g++ --version" gave "[WinError 2] The system cannot find the file specified"
Running "clang++ --version" gave "[WinError 2] The system cannot find the file specified"
`
How can I fix this?

**Comment by MuhdNurHidayat** [comment]
You need to at least install c++ or g++ compiler to build **anything**, not only to build using meson. The compilers are available under cygwin package manager for Windows. And make sure the compiler's path is added to system variable so that other programs like meson could use the compilers.

Though I also seems to stuck at building the project, in my case it is problem with ninja (yes, you also need to install [ninja](https://github.com/ninja-build/ninja/releases/tag/v1.8.2), not just meson).

On my side, meson seems to not have problem:
<details><summary>The output from meson</summary><p>

```
The Meson build system
Version: 0.47.1
Source dir: W:\works\EasyRP
Build dir: W:\works\EasyRP\buildir
Build type: native build
Project name: EasyRP
Project version: 3.0
Native C++ compiler: c++ (gcc 7.3.0 "c++ (GCC) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Library discord-rpc found: YES
Build targets in project: 2
Found ninja-1.8.2 at 'C:\ninja\ninja.EXE'
```
</p></details>
.

However when running ninja, it failed as:
<details><summary>Output from ninja</summary><p>

```
[5/5] Linking target easyrp.exe.
FAILED: easyrp.exe
c++ @easyrp.exe.rsp
easyrp@exe/discord.cpp.obj: In function `refreshDiscord()':
/cygdrive/w/works/EasyRP/buildir/../discord.cpp:88: undefined reference to `Disc
ord_UpdateConnection'
/cygdrive/w/works/EasyRP/buildir/../discord.cpp:88:(.text+0x3ed): relocation tru
ncated to fit: R_X86_64_PC32 against undefined symbol `Discord_UpdateConnection'

collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
</details>
.
 
I'm guessing the library file `discord-rpc.lib` the author originally used is different from the library file that I use.

**Comment by Pizzabelly** [comment]
@MuhdNurHidayat is correct you need a c++ compiler ;). For the link error I have updated the readme with build instructions. The important thing to fix the Discord_UpdateConnection part is to pass -DENABLE_IO_THREAD=OFF to cmake when building discord-rpc.

**Comment by seasew** [comment]
I'm still getting the link issue even when I build discord-rpc with DENABLE_IO_THREAD. Any idea what could be happening?

**Edit:** actually, I realized I need the c++ compiler. Not a link error yet.
